import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner"

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", geist.variable)}
    >
     <AuthProvider>
       <body className="min-h-full flex flex-col">{children}<Toaster
  position="top-center"        // top-center works best on mobile
  richColors                   // enables colored success/error styles
  closeButton                  // adds an X button
  toastOptions={{
    style: {
      borderRadius: "12px",
      fontSize: "14px",
      padding: "12px 16px",
    },
    classNames: {
      error: "bg-red-50 text-red-800 border border-red-200",
      success: "bg-green-50 text-green-800 border border-green-200",
      warning: "bg-yellow-50 text-yellow-800 border border-yellow-200",
    },
  }}
/></body>
       
     </AuthProvider>
    </html>
  );
}
